# Generated by Django 3.2.5 on 2021-07-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=25)),
                ('python_tip', models.CharField(max_length=140)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=25)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Python Tip',
                'verbose_name_plural': 'Python Tips',
            },
        ),
    ]
