# Generated by Django 3.2.5 on 2021-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonTipUserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_tip', models.CharField(max_length=140)),
                ('twitter_handle', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Python Tip User Form',
                'verbose_name_plural': 'Python Tips User Forms',
            },
        ),
        migrations.RenameModel(
            old_name='PythonTip',
            new_name='PythonTipSheet',
        ),
        migrations.AlterModelOptions(
            name='pythontipsheet',
            options={'verbose_name': 'Python Tip Sheet', 'verbose_name_plural': 'Python Tips Sheet'},
        ),
    ]
