# Generated by Django 3.2.5 on 2021-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0002_auto_20210706_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythontipsheet',
            name='author',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pythontipsheet',
            name='python_tip',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='pythontipsheet',
            name='timestamp',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='python_tip',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
