# Generated by Django 3.2.5 on 2021-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0003_auto_20210707_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythontipsheet',
            name='author',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pythontipsheet',
            name='python_tip',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='pythontipsheet',
            name='timestamp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='python_tip',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='pythontipuserform',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
