# Generated by Django 3.2.5 on 2021-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0004_auto_20210707_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythontipsheet',
            name='link',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
